task:
  name: Construction du paquet test
  freebsd_instance:
    image_family: freebsd-14-2
  install_script:
    - sudo pkg install -y pkg
  script:
    - cd test && sh ./build.sh
  artifacts:
    repo:
      path: test/repo

