freebsd_instance:
  image_family: freebsd-13-2

task:
  name: Build FreeBSD pkg
  install_script:
    - sudo pkg install -y git pkg
  script:
    - sh ./build.sh
  artifacts:
    repo:
      path: repo

