task:
  name: Build pfSense Packages
  freebsd_instance:
    image_family: freebsd-14-2

  install_script:
    - sudo pkg install -y pkg git bash jq 

  script:
    - echo "🛠  Creating and populating repository..."
    - |
       # Run the script to populate the repo and generate metadata
       bash ./create_repo.sh

  artifacts:
  - path: repo
    destination: repo  # Optional: The destination where the artifact will be uploaded in your CI system

  env:
    GH_TOKEN: ENCRYPTED[GH_TOKEN]


  post_script:
    # Git configuration for pushing to GitHub
    - git config --global user.name "Cirrus CI"
    - git config --global user.email "ci@cirrus-ci.com"

    # Clone the repository
    - git clone https://bonomani:${GH_TOKEN}@github.com/bonomani/pkgsense.git ci-build
    - cd ci-build

    # Fetch all branches
    - git fetch --all

    # Check if the ci-build branch exists remotely, create it if it doesn't
    - |
      if ! git show-ref --verify --quiet refs/remotes/origin/ci-build; then
        echo "The 'ci-build' branch does not exist. Creating it..."
        git checkout -b ci-build  # Create and checkout the new branch
        git push origin ci-build  # Push the new branch to the remote
      else
        echo "The 'ci-build' branch already exists."
        git checkout ci-build  # Checkout the existing branch
      fi

    # Ensure the repo folder exists and copy the built packages to the ci-build branch
    - |
      if [ -d "../repo" ]; then
        cp -r ../repo/* ./  # Copy the contents of the repo directory to the current (ci-build) directory
        echo "✅ Copied built packages to ci-build."
      else
        echo "🚨 'repo' directory does not exist, skipping copy operation."
      fi

    # Commit and push changes to the ci-build branch
    - git add .
    - git commit -m "🔄 Auto-publish pfSense packages from Cirrus CI"
    - git push origin ci-build

    # Display the result URLs dynamically
    - echo "🌐 Packages pushed to: https://github.com/bonomani/pkgsense/tree/ci-build"

