freebsd_instance:
  image: freebsd-13-2

freebsd_build:
  name: Build FreeBSD .txz
  instance: freebsd_instance
  install_script:
    - sudo pkg install -y git pkg
  script:
    - sh ./build.sh
  artifacts:
    repo:
      path: repo

