task:
  name: Build FreeBSD Package
  freebsd_instance:
    image_family: freebsd-14-2
  install_script:
    - sudo pkg install -y pkg
  script:
    - sh ./build.sh
  artifacts:
    repo:
      path: repo

