task:
  name: Build pfSense Packages
  freebsd_instance:
    image_family: freebsd-14-2

  install_script:
    - sudo pkg install -y pkg git bash jq 

  script:
    - echo "🛠 Building all pfSense packages..."
    - |
      # Loop through each package directory and build them dynamically
      for pkg_dir in packages/*; do
        if [ -d "$pkg_dir" ]; then
          cd "$pkg_dir"
          echo "Current directory: $(pwd)"
          echo "🛠 Building package: $(basename $pkg_dir)"
          bash ./build.sh  # Build each package dynamically
          cd .. 
        fi
      done

  artifacts:
    packages_repo:
      path: repo

  env:
    GH_TOKEN: ENCRYPTED[GH_TOKEN]

  post_script:
    # Git configuration for pushing to GitHub
    - git config --global user.name "Cirrus CI"
    - git config --global user.email "ci@cirrus-ci.com"
    - git clone --depth 1 --branch ci-build https://bonomani:${GH_TOKEN}@github.com/bonomani/pkgsense.git ci-build

    # Copy the built packages to the ci-build branch
    - cp -r repo/* ci-build/

    # Commit and push changes to the ci-build branch
    - cd ci-build
    - git add .
    - git commit -m "🔄 Auto-publish pfSense packages from Cirrus CI"
    - git push origin ci-build

    # Display the result URLs dynamically
    - echo "🌐 Packages pushed to: https://github.com/bonomani/pkgsense/tree/ci-build"

