task:
  name: Build and Deploy pfSense Test Package
  freebsd_instance:
    image_family: freebsd-14-2

  install_script:
    - sudo pkg install -y pkg git

  script:
    - cd test
    - echo "🛠  Building test package"
    - sh ./build.sh
    - cd ..

  artifacts:
    test_repo:
      path: test/repo

  env:
    GH_TOKEN: ENCRYPTED[GH_TOKEN]

  post_script:
    - echo ${GH_TOKEN} | cut -c 1-10
    - git config --global user.name "Cirrus CI"
    - git config --global user.email "ci@cirrus-ci.com"
    - git clone --depth 1 --branch gh-pages https://bonomani:${GH_TOKEN}@github.com/bonomani/pkgsense.git gh-pages
    - sh -c 'for dir in */repo; do cp -r "$dir"/* gh-pages/; done'
    - cd gh-pages
    - touch .nojekyll
    - git add .
    - git commit -m "🔄 Auto-publish test package from Cirrus CI" || echo "✅ Aucun changement à publier"
    - git remote set-url origin https://bonomani:${GH_TOKEN}@github.com/bonomani/pkgsense.git
    - git push origin gh-pages
    - echo "🌐 Déployé sur : https://bonomani.github.io/pkgsense/"
    - echo "📦 Package : https://bonomani.github.io/pkgsense/test-1.0.txz"
    - echo "📄 Index   : https://bonomani.github.io/pkgsense/packagesite.yaml"

