task:
  name: Build pfSense Packages
  freebsd_instance:
    image_family: freebsd-14-2

  install_script:
    - sudo pkg install -y pkg git bash jq 

  script:
    - echo "🛠  Creating and populating repository..."
    - |
       # Run the script to populate the repo and generate metadata
       bash ./create_repo.sh

  artifacts:
  - path: repo
    destination: repo  # Optional: The destination where the artifact will be uploaded in your CI system

  env:
    GH_TOKEN: ENCRYPTED[GH_TOKEN]
  post_script:
    # Git configuration for pushing to GitHub
    - git config --global user.name "Cirrus CI"
    - git config --global user.email "ci@cirrus-ci.com"

    # Step 1: Create /tmp/ci-build directory
    - mkdir -p /tmp/ci-build
    - cd /tmp/ci-build

    # Step 2: Clone the repository into /tmp/ci-build
    - git clone https://bonomani:${GH_TOKEN}@github.com/bonomani/pkgsense.git .

    # Step 3: Fetch all branches to ensure the ci-build branch is available
    - git fetch --all

    # Step 4: Check if the ci-build branch exists remotely, create it if it doesn't
    - |
      if ! git show-ref --verify --quiet refs/remotes/origin/ci-build; then
        echo "The 'ci-build' branch does not exist. Creating it..."
        git checkout -b ci-build  # Create and checkout the new branch
        git push origin ci-build  # Push the new branch to the remote
      else
        echo "The 'ci-build' branch already exists."
        git checkout ci-build  # Checkout the existing branch
      fi

    # Step 4.5: Remove all files in /tmp/ci-build except for the git-related files
    - |
      echo "🧹 Cleaning up non-git files in /tmp/ci-build..."
      find /tmp/ci-build -mindepth 1 ! -name '.git' -exec rm -rf {} +  # Remove all files except for .git directory

    # Step 5: Ensure the repo folder exists and copy the built packages to the ci-build branch
    - |
      if [ -d "/tmp/cirrus-ci-build/repo" ]; then
      # Move the entire 'repo' directory to the ci-build directory
        mv /tmp/cirrus-ci-build/repo /tmp/ci-build/
        echo "✅ Moved built packages to ci-build."
      else
        echo "🚨 'repo' directory does not exist, skipping move operation."
      fi

    # Step 6: Commit and push changes to the ci-build branch
    - git add .
    - git commit -m "🔄 Auto-publish pfSense packages from Cirrus CI"
    - git push origin ci-build

    # Step 7: Display the result URLs dynamically
    - echo "🌐 Packages pushed to: https://github.com/bonomani/pkgsense/tree/ci-build"
