name: Build pfSense Test Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: freebsd-latest
    name: Build on FreeBSD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build package
        run: |
          sudo pkg install -y pkg
          sh ./build.sh

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: test-package-repo
          path: repo/

