name: Build pfSense Test Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start FreeBSD builder via Cirrus
        uses: cirruslabs/github-action-freebsd@v1
        with:
          run: |
            sudo pkg install -y git pkg
            git clone https://github.com/bonomani/pkgsense.git /root/pkgsense
            cd /root/pkgsense
            sh ./build.sh

